--Sitters table seeds

INSERT INTO sitters (first_name, last_name, email, accepted_pet_type, availability_dates) VALUES ('Star', 'Daborn', 'sdaborn0@scientificamerican.com', ARRAY['dog'], '{2023-08-18, 2023-08-17, 2023-08-19, 2023-08-20, 2023-08-21, 2023-08-22}'::date[]);
INSERT INTO sitters (first_name, last_name, email, accepted_pet_type, availability_dates) VALUES ('Kaitlin', 'Pirrone', 'kpirrone1@dailymotion.com', ARRAY['dog', 'cat'], '{2023-08-30, 2023-08-20, 2023-08-21, 2023-08-22, 2023-08-23}'::date[]);
INSERT INTO sitters (first_name, last_name, email, accepted_pet_type, availability_dates) VALUES ('Sada', 'Orteaux', 'sorteaux2@bbc.co.uk', ARRAY['dog', 'cat'], '{2023-08-28}'::date[]);
INSERT INTO sitters (first_name, last_name, email, accepted_pet_type, availability_dates) VALUES ('Graig', 'Berrey', 'gberrey3@businessweek.com', ARRAY['dog', 'cat'], '{2023-08-19, 2023-08-30}'::date[]);
INSERT INTO sitters (first_name, last_name, email, accepted_pet_type, availability_dates) VALUES ('Curran', 'Lintot', 'clintot4@wikia.com', ARRAY['cat'], '{2023-08-24, 2023-08-19}'::date[]);
INSERT INTO sitters (first_name, last_name, email, accepted_pet_type, availability_dates) VALUES ('Yelena', 'Blazevic', 'yblazevic5@behance.net', ARRAY['dog', 'cat'], '{2023-08-30}'::date[]);
INSERT INTO sitters (first_name, last_name, email, accepted_pet_type, availability_dates) VALUES ('Robby', 'Ox', 'rox6@youtube.com', ARRAY['cat'], '{2023-08-19}'::date[]);
INSERT INTO sitters (first_name, last_name, email, accepted_pet_type, availability_dates) VALUES ('Mara', 'Tigwell', 'mtigwell7@chron.com', ARRAY['dog', 'cat'], '{2023-08-15, 2023-08-30}'::date[]);
INSERT INTO sitters (first_name, last_name, email, accepted_pet_type, availability_dates) VALUES ('Nolly', 'Scare', 'nscare8@narod.ru', ARRAY['dog', 'cat'], '{2023-08-20, 2023-08-21, 2023-08-22, 2023-08-26}'::date[]);
INSERT INTO sitters (first_name, last_name, email, accepted_pet_type, availability_dates) VALUES ('Gunar', 'Pomeroy', 'gpomeroy9@so-net.ne.jp', ARRAY['dog', 'cat'], '{2023-08-15, 2023-08-23}'::date[]);
INSERT INTO sitters (first_name, last_name, email, accepted_pet_type, availability_dates) VALUES ('Antony', 'Mougin', 'amougina@opensource.org', ARRAY['dog', 'cat'], '{2023-08-30}'::date[]);
INSERT INTO sitters (first_name, last_name, email, accepted_pet_type, availability_dates) VALUES ('Alanah', 'Cordero', 'acorderob@devhub.com', ARRAY['dog', 'cat'], '{2023-08-30, 2023-08-23}'::date[]);
INSERT INTO sitters (first_name, last_name, email, accepted_pet_type, availability_dates) VALUES ('Frederique', 'Hatchell', 'fhatchellc@macromedia.com', ARRAY['dog'], '{2023-08-15}'::date[]);
INSERT INTO sitters (first_name, last_name, email, accepted_pet_type, availability_dates) VALUES ('Marion', 'McCullogh', 'mmcculloghd@cnn.com', ARRAY['dog', 'cat'], '{2023-08-23}'::date[]);
INSERT INTO sitters (first_name, last_name, email, accepted_pet_type, availability_dates) VALUES ('Tonya', 'Davidovits', 'tdavidovitse@netvibes.com', ARRAY['dog', 'cat'], '{2023-08-21}'::date[]);
INSERT INTO sitters (first_name, last_name, email, accepted_pet_type, availability_dates) VALUES ('Claudius', 'Zanicchi', 'czanicchif@epa.gov', ARRAY['dog', 'cat'], '{2023-08-21}'::date[]);
INSERT INTO sitters (first_name, last_name, email, accepted_pet_type, availability_dates) VALUES ('Goran', 'Royston', 'groystong@ebay.co.uk', ARRAY['dog', 'cat'], '{2023-08-23}'::date[]);
INSERT INTO sitters (first_name, last_name, email, accepted_pet_type, availability_dates) VALUES ('Marthe', 'Grieswood', 'mgrieswoodh@usatoday.com', ARRAY['dog', 'cat'], '{2023-08-25}'::date[]);
INSERT INTO sitters (first_name, last_name, email, accepted_pet_type, availability_dates) VALUES ('Kacey', 'Creek', 'kcreeki@usatoday.com', ARRAY['dog', 'cat'], '{2023-08-18}'::date[]);
INSERT INTO sitters (first_name, last_name, email, accepted_pet_type, availability_dates) VALUES ('Frederique', 'Duffree', 'fduffreej@phoca.cz', ARRAY['dog', 'cat'], '{2023-08-29}'::date[]);
INSERT INTO sitters (first_name, last_name, email, accepted_pet_type, availability_dates) VALUES ('Theodor', 'Warhurst', 'twarhurstk@google.co.jp', ARRAY['dog', 'cat'], '{2023-08-19}'::date[]);
INSERT INTO sitters (first_name, last_name, email, accepted_pet_type, availability_dates) VALUES ('Lucretia', 'Cabotto', 'lcabottol@tmall.com', ARRAY['dog', 'cat'], '{2023-08-26}'::date[]);
INSERT INTO sitters (first_name, last_name, email, accepted_pet_type, availability_dates) VALUES ('Mack', 'Jewar', 'mjewarm@hexun.com', ARRAY['dog', 'cat'], '{2023-08-30}'::date[]);
INSERT INTO sitters (first_name, last_name, email, accepted_pet_type, availability_dates) VALUES ('Farand', 'Reisen', 'freisenn@slashdot.org', ARRAY['dog', 'cat'], '{2023-08-19}'::date[]);
INSERT INTO sitters (first_name, last_name, email, accepted_pet_type, availability_dates) VALUES ('Zacherie', 'Trownson', 'ztrownsono@fastcompany.com', ARRAY['dog', 'cat'], '{2023-08-15}'::date[]);
INSERT INTO sitters (first_name, last_name, email, accepted_pet_type, availability_dates) VALUES ('Maxim', 'Bock', 'mbockp@comcast.net', ARRAY['dog', 'cat'], '{2023-08-27}'::date[]);
INSERT INTO sitters (first_name, last_name, email, accepted_pet_type, availability_dates) VALUES ('Ulla', 'Ashe', 'uasheq@nhs.uk', ARRAY['dog', 'cat'], '{2023-08-18, 2023-08-23}'::date[]);
INSERT INTO sitters (first_name, last_name, email, accepted_pet_type, availability_dates) VALUES ('Ozzy', 'Duthy', 'oduthyr@mit.edu', ARRAY['dog', 'cat'], '{2023-08-18}'::date[]);
INSERT INTO sitters (first_name, last_name, email, accepted_pet_type, availability_dates) VALUES ('Camey', 'Abatelli', 'cabatellis@noaa.gov', ARRAY['dog', 'cat'], '{2023-08-26}'::date[]);
INSERT INTO sitters (first_name, last_name, email, accepted_pet_type, availability_dates) VALUES ('Carine', 'Cucinotta', 'ccucinottat@washington.edu', ARRAY['dog', 'cat'], '{2023-08-17}'::date[]);